# Set up and run this Streamlit App
import streamlit as st
# from helper_functions import llm # <--- This is the helper function that we have created 🆕
from logics import customer_query_handler # <--- This is the helper function that we have created
import json
import pandas as pd

from helper_functions.utility import check_password  

# Check if the password is correct.  
if not check_password():  
    st.stop()

# region <--------- Streamlit App Configuration --------->
st.set_page_config(
    layout="centered",
    page_title="My Streamlit App"
)
# endregion <--------- Streamlit App Configuration --------->

st.title("Streamlit App")

form = st.form(key="form", clear_on_submit=True)
form.subheader("Prompt")

user_prompt = form.text_area("Enter your prompt here", height=200)

if form.form_submit_button("Submit"):
    st.toast(f"User Input Submitted - {user_prompt}")
    response = customer_query_handler.process_user_message(user_prompt) # <--- This calls the helper function that we have created 🆕
    st.write(response[-1]) # <--- This displays the response generated by the LLM onto the frontend 🆕        
    print(response)
    print(f"User Input is {user_prompt}")
    if("Unfortunately" not in response[-1]):
        data_dump = json.dumps(response[1].replace("```json", "").replace("```", "")) # <--- This displays the response generated
        data = json.loads(data_dump)
        df = pd.DataFrame(eval(data))
        st.dataframe(df)